name: 'ecommerce_analytics'
version: '1.0.0'
config-version: 2


profile: 'default'


model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

models:
  ecommerce_analytics:
    +materialized: view
    bronze:
      +database: bronze
      +schema: ecommerce
      +materialized: table
    silver:
      +database: silver
      +schema: ecommerce
      +materialized: table
    gold:
      +database: gold
      +schema: ecommerce
      +materialized: view
